import {createHash} from 'node:crypto';
import {mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import path from 'node:path';
import {TreeSnapshots} from '../session/snapshots.js';
import {reinHome} from '../store/paths.js';
import {readSpec, readStage, specDir, type Task} from './store.js';

/**
 * Spec-to-code traceability: when a task starts, the tree is recorded (in a private store, like
 * /rewind's, never the project's .git); when it's done, the lines that changed since are written to
 * the spec's trace.json against the task and its requirements, and trace.md is regenerated:
 * requirement → task → file:lines, for the reviewer.
 */
export type TraceEntry = {task: string; reqs: string[]; text: string; at: string; files: {file: string; ranges: [number, number][]}[]};

const startsFile = () => path.join(reinHome(), 'checkpoints', 'spec-trace', 'starts.json');
const key = (root: string, spec: string, task: string) => `${path.resolve(root)}|${spec}|${task}`;
const store = (root: string) => new TreeSnapshots(root, () => 'spec-trace', createHash('sha1').update(path.resolve(root)).digest('hex').slice(0, 12));

function starts(): Record<string, string> {
  try {
    return JSON.parse(readFileSync(startsFile(), 'utf8'));
  } catch {
    return {};
  }
}
function saveStarts(s: Record<string, string>): void {
  mkdirSync(path.dirname(startsFile()), {recursive: true});
  writeFileSync(startsFile(), JSON.stringify(s));
}

/** Record where a task starts from. `workRoot` is where the code is (a subagent's worktree, or the project). */
export async function startTask(workRoot: string, spec: string, task: string): Promise<void> {
  const tree = await store(workRoot).tree();
  const s = starts();
  s[key(workRoot, spec, task)] = tree;
  // The latest start in this folder also stands in for tasks marked done without one.
  s[key(workRoot, spec, '*')] = tree;
  saveStarts(s);
}

/** The lines changed since the task started (or since the last recorded point in this folder). */
export async function taskChanges(workRoot: string, spec: string, task: string): Promise<TraceEntry['files'] | undefined> {
  const s = starts();
  const from = s[key(workRoot, spec, task)] ?? s[key(workRoot, spec, '*')];
  if (!from) return undefined;
  const st = store(workRoot);
  const now = await st.tree();
  s[key(workRoot, spec, '*')] = now;
  delete s[key(workRoot, spec, task)];
  saveStarts(s);
  // The spec's own files aren't the code it traces to.
  return (await st.hunks(from, now)).filter((f) => !f.file.startsWith('.rein/'));
}

const traceJson = (root: string, spec: string) => path.join(specDir(root, spec), 'trace.json');

export function readTrace(root: string, spec: string): TraceEntry[] {
  try {
    return JSON.parse(readFileSync(traceJson(root, spec), 'utf8'));
  } catch {
    return [];
  }
}

export function recordTrace(root: string, spec: string, task: Task, files: TraceEntry['files']): void {
  const entries = readTrace(root, spec).filter((e) => e.task !== task.id);
  entries.push({task: task.id, reqs: task.reqs, text: task.text, at: new Date().toISOString(), files});
  writeFileSync(traceJson(root, spec), JSON.stringify(entries, null, 2) + '\n');
  writeFileSync(path.join(specDir(root, spec), 'trace.md'), traceMarkdown(root, spec, entries));
}

const lines = (r: [number, number]) => (r[0] === r[1] ? `${r[0]}` : `${r[0]}-${r[1]}`);

/** requirement → tasks → file:lines, and the requirements nothing traces to yet. */
export function traceMarkdown(root: string, spec: string, entries = readTrace(root, spec)): string {
  const s = readSpec(root, spec);
  const reqText = readStage(root, spec, 'requirements')?.text ?? '';
  const reqIds = [...new Set(reqText.match(/\bR\d+(?:\.\d+)?\b/g) ?? [])];
  const byReq = new Map<string, TraceEntry[]>();
  for (const e of entries) for (const r of e.reqs.length ? e.reqs : ['(no requirement)']) byReq.set(r, [...(byReq.get(r) ?? []), e]);
  const out = [`# Traceability: ${s?.title ?? spec}`, '', 'Generated by Rein as tasks finish: each requirement, the tasks that met it, and the lines they changed.', ''];
  for (const r of [...reqIds, ...[...byReq.keys()].filter((k) => !reqIds.includes(k))]) {
    const es = byReq.get(r);
    out.push(`## ${r}`, '');
    if (!es?.length) {
      out.push('Nothing traces to this requirement yet.', '');
      continue;
    }
    for (const e of es) {
      out.push(`- **${e.task}** ${e.text}`);
      for (const f of e.files) out.push(`  - \`${f.file}\`${f.ranges.length ? `: ${f.ranges.map(lines).join(', ')}` : ''}`);
      if (!e.files.length) out.push('  - (no file changes recorded)');
    }
    out.push('');
  }
  return out.join('\n');
}
